function drawFooter(pdf) {
  pdf.setDrawColor(...COLORS.border);

  pdf.line(20, 285, 190, 285);

  pdf.setFontSize(9);

  pdf.setTextColor(120);

  pdf.text("Generated by Page Pulse • React • Express • Tailwind CSS", 20, 291);

  pdf.text("© 2026 Ninaad Mhadalkar", 150, 291);
}
